image:
  file: .gitpod.Dockerfile

tasks:
   - name: ggg
     command: |
      streamlit run ./gui/streamlit_app.py --browser.gatherUsageStats false
ports:
  - port: 8501
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
